// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXm0beQURHqM1f1DQuWPKR1bMyWwQ0h4E',
    appId: '1:255688407055:web:5648f83cc4ed39c132cb7a',
    messagingSenderId: '255688407055',
    projectId: 'agriculture-pest-system-96401',
    authDomain: 'agriculture-pest-system-96401.firebaseapp.com',
    storageBucket: 'agriculture-pest-system-96401.firebasestorage.app',
    measurementId: 'G-KGWTNHEMVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVVa5PzCiViDmkuyiB4v3kc-VouwDh-o',
    appId: '1:255688407055:android:702363255b22972032cb7a',
    messagingSenderId: '255688407055',
    projectId: 'agriculture-pest-system-96401',
    storageBucket: 'agriculture-pest-system-96401.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0gFC8Zs3dCu5-n3yWmJPGXQR4nbWw630',
    appId: '1:255688407055:ios:454997510a66271e32cb7a',
    messagingSenderId: '255688407055',
    projectId: 'agriculture-pest-system-96401',
    storageBucket: 'agriculture-pest-system-96401.firebasestorage.app',
    iosBundleId: 'com.example.agriculturePestSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0gFC8Zs3dCu5-n3yWmJPGXQR4nbWw630',
    appId: '1:255688407055:ios:454997510a66271e32cb7a',
    messagingSenderId: '255688407055',
    projectId: 'agriculture-pest-system-96401',
    storageBucket: 'agriculture-pest-system-96401.firebasestorage.app',
    iosBundleId: 'com.example.agriculturePestSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXm0beQURHqM1f1DQuWPKR1bMyWwQ0h4E',
    appId: '1:255688407055:web:5437edee90c39dcf32cb7a',
    messagingSenderId: '255688407055',
    projectId: 'agriculture-pest-system-96401',
    authDomain: 'agriculture-pest-system-96401.firebaseapp.com',
    storageBucket: 'agriculture-pest-system-96401.firebasestorage.app',
    measurementId: 'G-JVZELE9JGX',
  );
}
